More CI Integrations cripts, update of frontend and backend to v1.1.0. Containing fixes for fortify plugin integration and display of CI jobs on dashboard

diff --git a/scripts/CIScriptsFortify/mixeway-ci-fortify-mvn b/scripts/CIScriptsFortify/mixeway-ci-fortify-mvn
--- a/scripts/CIScriptsFortify/mixeway-ci-fortify-mvn
+++ b/scripts/CIScriptsFortify/mixeway-ci-fortify-mvn
@@ -1,12 +1,12 @@
 #!/bin/bash
 
 print_help() {
-  pritnf "Mixeway Request script, is contacting with Mixeway REST API in order to request SAST scan and later it verify results found during scanning of source code and OpenSource
+  pritnf "Mixeway Fortify CI MVN script, is contacting with Mixeway REST API in order to request SAST scan, OpenSource scan and later it verify results found during scanning of source code and OpenSource
   Libraries\n\n\n"
   printf "Example usage:\nmixeway-ci --appname=projectName --groupname=groupName --mixewayurl=http://mixeway.io --mixewayapikey=123 --mixewayprojectid=1 --skipsast --skipopensource"
   printf "\nRequired:\n"
   printf "    --appname - Subject application name\n"
-  printf "    --groupname - Mixeway Group name build name\n"
+  printf "    --groupname - Fortify SCA build name\n"
   printf "    --mixewayurl - URL for Mixeway API\n"
   printf "    --mixewayapikey - API key generated on Mixeway to authenticate call\n"
   printf "    --mixewayprojectid - ID of project on Mixeway\n"
@@ -15,6 +15,14 @@ print_help() {
 }
 if ! type jq > /dev/null; then
   echo "JQ has to be installed in order to run this script. Please install jq and try again."
+  exit 2
+fi
+if ! type sourceanalyzer > /dev/null; then
+  echo "Fortify SCA (sourceanalyzer command) has to be installed in order to run this script. Please install sourceanalyzer and try again."
+  exit 2
+fi
+if ! type cloudscan > /dev/null; then
+  echo "Fortify SCA (cloudscan command) has to be installed in order to run this script. Please install cloudscan and try again."
   exit 2
 fi
 if ! type curl > /dev/null; then
@@ -63,13 +71,34 @@ done
 get_commit_id() {
   COMMITID=$(git rev-parse HEAD)
 }
+fortify_clean() {
+  echo "Cleaning project files for $group_name"
+  sourceanalyzer -b $group_name -clean
+}
+fortify_translate() {
+  echo "Translating $group_name ..."
+  sourceanalyzer -b $group_name mvn package -DskipTests
+}
+fortify_cloudscan() {
+  echo "Sending Scan to cloudscan for  $group_name ..."
+  cloudscan -sscurl $SAST_URL -ssctoken $SAST_TOKEN start -upload -versionid $SAST_VERSIONID -b $group_name -uptoken $SAST_TOKEN -scan
+}
+#TODO
+get_sast_config(){
+  SAST_RESPONSE=$(curl -k -s --request GET --url $mixeway_url/v2/api/show/project/$mixeway_project_id/sast/$group_name/$app_name --header 'apikey: '"$mixeway_api_key"'')
+  INTEGRATION_SAST=$(echo SAST_RESPONSE | jq -r '.openSourceScannerIntegration') #TODO
+  if [ "$INTEGRATION_SAST" = "true" ]; then
+    echo "SAST scanner is avaliable proceeding..."
+    SAST_URL=$(echo $SAST_RESPONSE | jq -r '.openSourceScannerApiUrl') #TODO
+    SAST_TOKEN=$(echo $SAST_RESPONSE | jq -r '.openSourceScannerProjectId') #TODO
+    SAST_VERSIONID=$(echo $SAST_RESPONSE | jq -r '.openSourceScannerCredentials') #TODO
+  else
+    echo "SAST Scan was requested but there no integration between given project and SAST scanner"
+  fi
+}
 init_ci_job() {
   echo "Initializing CI job"
   curl -k -s --request GET --url $mixeway_url/v2/api/cicd/project/$mixeway_project_id/code/init/$group_name/$app_name/$COMMITID --header 'apikey: '"$mixeway_api_key"'' --output /dev/null
-}
-run_sast() {
-  echo "Request for a SAST"
-  curl -k -s --request PUT --url $mixeway_url/v2/api/cicd/project/$mixeway_project_id/code/scan/$group_name/$app_name/$COMMITID --header 'apikey: '"$mixeway_api_key"'' --output /dev/null
 }
 send_bom() {
   POSTDATA="{\"project\":\"$OS_ID\",\"bom\":\"$BOM\"}"
@@ -81,6 +110,12 @@ send_bom() {
     -d @- "$OS_URL/api/v1/bom" <<CURL_DATA
       $POSTDATA
 CURL_DATA
+}
+run_sast(){
+  get_sast_config
+  fortify_clean
+  fortify_translate
+  fortify_cloudscan
 }
 run_opensource() {
   echo "Getting OpenSource Vulnerability scanner integration info"
@@ -98,21 +133,6 @@ run_opensource() {
       if [ "$TECH" = "mvn" ]; then
         mvn org.cyclonedx:cyclonedx-maven-plugin:makeAggregateBom > /dev/null
         BOM=$(base64 target/bom.xml |tr -d \\n)
-        send_bom
-      elif [ "$TECH" = "js" ]; then
-        npm install --save ignore-errors
-        cyclonedx-bom -o bom.xml
-        BOM=$(base64 bom.xml |tr -d \\n)
-        send_bom
-      elif [ "$TECH" = "php" ]; then
-        composer require --dev cyclonedx/cyclonedx-php-composer --ignore-platform-reqs
-        composer make-bom
-        BOM=$(base64 bom.xml |tr -d \\n)
-        send_bom
-      elif [ "$TECH" = "python" ] ; then
-        pip freeze > requirements.txt
-        cyclonedx-py -i requirements.txt -o bom.xml
-        BOM=$(base64 bom.xml |tr -d \\n)
         send_bom
       else
           echo "Unknown project tech. Supported: MVN, JS, Python, PHP"
